version: '3.8'

services:

  postgr:    
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: root 
      POSTGRES_DB: projetnosql 
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    restart: always

  mongod:
    image: 'mongo:latest'
    ports:
      - 27017:27017
    restart: always
  
  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - '5000:5000'
    depends_on:
      - postgr
      - mongod   
    links:
      - "postgr:postgresql"

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - '3000:3000'
    tty: true
    depends_on:
      - postgr
      - mongod 
    links:
      - "postgr:postgresql"

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"